baseURL: https://brvy.space
languageCode: en-us
title: brvy.space
theme: PaperMod
paginate: 5

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: G-91SMSJ0V50

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: brvy.space
  description: "we were never being boring"
  # keywords: [Blog, Portfolio, PaperMod]
  author: Alfred Dobradi
  # author: ["Me", "You"] # multiple authors
  # images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    # favicon: "<link / abs url>"
    # favicon16x16: "<link / abs url>"
    # favicon32x32: "<link / abs url>"
    # apple_touch_icon: "<link / abs url>"
    # safari_pinned_tab: "<link / abs url>"

  # label:
  #   text: "Home"
  #   icon: /apple-touch-icon.png
  #   iconHeight: 35

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: brvy.space
    subtitle: "programming and baseball"
    imageUrl: "/img/ballin.png"
    imageWidth: 200
    imageHeight: 200
    imageTitle: Good job!
    buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tags

  # home-info mode
  # homeInfoParams:
  #   Title: "Hi there \U0001F44B"
  #   Content: Welcome to my blog

  socialIcons:
    - name: github
      url: "https://github.com/alfreddobradi"
    - name: discogs
      url: "https://discogs.com/user/barveyhirdman"
    - name: medium
      url: "https://medium.com/non-league-legends"
    - name: reddit
      url: "https://reddit.com/user/barveyhirdman"
    - name: twitch
      url: "https://twitch.tv/barveyhirdman"

  # analytics:
  #   google:
  #     SiteVerificationTag: "XYZabc"
  #   bing:
  #     SiteVerificationTag: "XYZabc"
  #   yandex:
  #     SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  # editPost:
  #   URL: "https://github.com/<path_to_repo>/content"
  #   Text: "Suggest Changes" # edit text
  #   appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: tags
      name: tags
      url: /tags/
      weight: 20
    - identifier: home
      name: home
      url: https://brvy.space
      weight: 30