name: Build Docker image
on:
  workflow_dispatch:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      -
        name: Lowercase repo owner
        run: |
          echo "OWNER=${GITHUB_REPOSITORY_OWNER,,}" >>${GITHUB_ENV}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - 
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_PAT }}
      - 
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          platforms: linux/amd64,linux/arm64,darwin/arm64
          push: true
          tags: |
            alfreddobradi/blog.brvy.space:${{ github.ref_name }}
            alfreddobradi/blog.brvy.space:latest
            ghcr.io/alfreddobradi/blog.brvy.space:${{ github.ref_name }}
            ghcr.io/alfreddobradi/blog.brvy.space:latest