name: Build Docker image
on:
  workflow_dispatch:
  release:
    types:
      - published

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-20.04
    steps:
    - run: |
        echo "Ref: ${{ github.ref_name }}"